services:
  goshort:
    image: goshort
    build:
      context: .
      dockerfile: ./docker/goshort.Dockerfile
    hostname: goshort
    environment:
      GOSHRT_CONFIG_PATH: /etc/goshort
      GOSHRT_CONFIG_NAME: config.dev
    ports:
      - 8080:8080
    volumes:
      - ./config:/etc/goshort

  goshort-analytics:
    image: goshort-analytics
    hostname: goshort-analytics
    build:
      context: .
      dockerfile: ./docker/goshort-analytics.Dockerfile
    environment:
      GOSHRT_CONFIG_PATH: /etc/goshort-analytics
      GOSHRT_CONFIG_NAME: analytics.dev
    volumes:
      - ./config:/etc/goshort-analytics

  goshort-cache:
    image: goshort-cache
    hostname: cache
    build:
      context: .
      dockerfile: ./docker/cache.Dockerfile
    environment:
      GOSHRT_CONFIG_PATH: /etc/goshort-cache
      GOSHRT_CONFIG_NAME: cache.dev
    volumes:
      - ./config:/etc/goshort-cache
    depends_on:
      - redis

  redis:
    image: redis:7.2.5-alpine
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512m
        reservations:
          cpus: "0.25"
          memory: 256m

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - 2181:2181
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512m
        reservations:
          cpus: "0.25"
          memory: 256m

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
#      KAFKA_JMX_PORT: 19192
#      KAFKA_JMX_HOSTNAME: kafka
#    ports:
#      - 29092:29092
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512m
        reservations:
          cpus: "0.25"
          memory: 256m

#  kafka-ui:
#    container_name: kafka-ui
#    depends_on:
#      - kafka
#    image: provectuslabs/kafka-ui
#    ports:
#      - 8090:8080
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: INTERNAL://kafka:19092
#      KAFKA_CLUSTERS_0_METRICS_PORT: 19192

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
      - zookeeper
    entrypoint: ["/bin/sh", "-c"]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128m
    command: |
      "
      echo -e 'Init kafka'
      kafka-topics  --bootstrap-server kafka:19092 --create --topic url.events --replication-factor 1 --partitions 1
      
      echo -e 'Init done'
      kafka-topics --bootstrap-server kafka:19092 --list
      "

  prometheus:
    image: prom/prometheus
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512m
        reservations:
          cpus: "0.25"
          memory: 256m
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
