global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "goshort-analytics"
    static_configs:
      - targets: [ "goshort-analytics:8081" ]
        labels:
          app: "goshort"
    metrics_path: "/metrics"